name: Produce build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-2025

    env:
      projName: w10mu
      buildCfg: Release
      net45SdkUrl: 'https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net45/1.0.3'
      sdkSystemPath: 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'

    steps:
      - name: Install .NET Framework 4.5 SDK
        shell: pwsh
        run: |
          echo "download ${env:net45SdkUrl}"
          Invoke-WebRequest -Uri "${env:net45SdkUrl}" -OutFile "${env:temp}\net45sdk.zip"
          echo "unzip net45sdk.zip"
          Expand-Archive -Force -LiteralPath "${env:temp}\net45sdk.zip" -DestinationPath "${env:temp}\net45sdk"
          echo "delete ${env:sdkSystemPath}\v4.5"
          [IO.Directory]::Delete("${env:sdkSystemPath}\v4.5", $True)
          echo "move SDK to ${env:sdkSystemPath}\v4.5"
          Move-Item -Force -LiteralPath "${env:temp}\net45sdk\build\.NETFramework\v4.5" -Destination "${env:sdkSystemPath}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages
        run: nuget restore ${env:projName}.sln

      - name: Build
        run: msbuild ${env:projName}.sln -p:Configuration=${env:buildCfg}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: bin\Release\${{env.projName}}.exe